import { createFileRoute } from "@tanstack/react-router";
import { createClient } from "@supabase/supabase-js";

/**
 * GET /api/context/$token -> plain-text project context snapshot.
 *
 * This is the URL generated by the Connectors tab. It's intentionally
 * public/unauthenticated (protected only by the token being an
 * unguessable random secret, the same trust model as a Google Docs share
 * link) so that external tools like Claude or ChatGPT — which have no
 * Zeus AI session — can fetch it directly when a user pastes the link.
 */
export const Route = createFileRoute("/api/context/$token")({
  server: {
    handlers: {
      GET: async ({ params }) => {
        try {
          const SUPABASE_URL = process.env.SUPABASE_URL!;
          const SUPABASE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY!;
          const supabase = createClient(SUPABASE_URL, SUPABASE_KEY, {
            auth: { persistSession: false, autoRefreshToken: false },
          });

          // Uses a SECURITY DEFINER RPC (not a direct table select) so the
          // token is the only thing that can unlock a row — see
          // supabase/migrations/20260726093000_fix_project_context_token_leak.sql
          // for why a direct `.from('project_contexts').select()` with the
          // anon key was a full-table-read bypass.
          const { data, error } = await supabase
            .rpc("get_project_context_by_token", { p_token: params.token })
            .maybeSingle();

          if (error) throw error;
          const ctx = data as unknown as {
            project_name: string;
            created_at: string;
            content: string;
          } | null;
          if (!ctx) {
            return new Response("Not found. This context link may have been deleted.", {
              status: 404,
              headers: { "Content-Type": "text/plain; charset=utf-8" },
            });
          }

          const body =
            `# Zeus AI Project Context — ${ctx.project_name}\n` +
            `# Generated: ${ctx.created_at}\n` +
            `#\n` +
            `# Paste this whole page into Claude, ChatGPT, or any AI coding assistant\n` +
            `# so it has the same context Zeus AI does for this project.\n\n` +
            ctx.content;

          return new Response(body, {
            status: 200,
            headers: {
              "Content-Type": "text/plain; charset=utf-8",
              "Cache-Control": "no-store",
            },
          });
        } catch (error) {
          const message = error instanceof Error ? error.message : "Unexpected error";
          return new Response(`Error loading project context: ${message}`, {
            status: 500,
            headers: { "Content-Type": "text/plain; charset=utf-8" },
          });
        }
      },
    },
  },
});
