-- Phase 3: Project Modification + Diff Viewer.
--
-- A "modification" is a proposed set of file changes (create/modify/delete)
-- generated by Zeus AI for an indexed workspace project, shown to the user
-- as a diff before anything is written. Only once the user clicks Apply do
-- the changes land in workspace_project_files.
--
-- `files` holds one entry per changed file:
--   { path, action: 'create'|'modify'|'delete', reason, before, after }
-- `before`/`after` are full file contents (not diffs) so the UI can render
-- a line-level diff and so applying/rolling back is a straight write.
create table if not exists public.workspace_modifications (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.workspace_projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  instructions text not null,
  summary text not null default '',
  status text not null default 'proposed' check (status in ('proposed', 'applied')),
  files jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  applied_at timestamptz
);

comment on table public.workspace_modifications is
  'Proposed and applied AI-generated modifications for a Project Workspace project (Phase 3). Holds full before/after content per changed file so the diff viewer and apply step never need to re-derive it.';

create index if not exists workspace_modifications_project_id_idx on public.workspace_modifications (project_id);
create index if not exists workspace_modifications_user_id_idx on public.workspace_modifications (user_id);

alter table public.workspace_modifications enable row level security;

create policy "Users manage their own workspace modifications"
  on public.workspace_modifications
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
