// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Set them in your deployment's environment configuration (see .env.example).`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    // Try Bearer token first (API routes / desktop app)
    const authHeader = request.headers.get("authorization");
    let token: string | null = null;

    if (authHeader?.startsWith("Bearer ")) {
      token = authHeader.replace("Bearer ", "");
    }

    // Fallback: extract Supabase session from cookies (TanStack Start server functions)
    if (!token) {
      const cookieHeader = request.headers.get("cookie") ?? "";
      const cookies = Object.fromEntries(
        cookieHeader.split(";").map((c) => {
          const [k, ...v] = c.trim().split("=");
          return [k, v.join("=")];
        }),
      );
      // Supabase stores the session in sb-<ref>-auth-token or similar cookie
      const authCookieKey = Object.keys(cookies).find((k) => k.includes("auth-token"));
      if (authCookieKey) {
        try {
          const sessionData = JSON.parse(decodeURIComponent(cookies[authCookieKey]));
          token = sessionData?.access_token ?? null;
        } catch {
          // Ignore parse errors
        }
      }
    }

    // Last resort: try to create a Supabase client with cookies and get session
    if (!token) {
      const supabaseAnon = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
        global: {
          headers: {
            cookie: request.headers.get("cookie") ?? "",
          },
        },
      });
      const { data: { session } } = await supabaseAnon.auth.getSession();
      if (session?.access_token) {
        token = session.access_token;
      }
    }

    if (!token) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error("Unauthorized: Invalid token");
    }

    if (!data.claims.sub) {
      throw new Error("Unauthorized: No user ID found in token");
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
        token,
      },
    });
  },
);
